FROM golang:1.23-alpine AS builder

WORKDIR /app

# --- DEĞİŞİKLİK BURADA ---
# go.mod, go.sum VE vendor klasörünü kopyalıyoruz
COPY go.mod go.sum ./
COPY vendor/ ./vendor/

# Artık 'go mod download' YAPMIYORUZ.
# Onun yerine build alırken '-mod=vendor' diyoruz.
COPY . .
RUN go build -mod=vendor -o analyst cmd/analyst/main.go
# -------------------------

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/web ./web 
COPY --from=builder /app/analyst .
CMD ["./analyst"]