# --- Aşama 1: İnşaat (Builder) ---
# '1.22' yerine direkt 'alpine' diyerek en son sürümü alıyoruz
FROM golang:alpine AS builder

WORKDIR /app

# go.mod dosyasını kopyala
COPY go.mod ./

# Şimdilik dış kütüphane kullanmadığımız için bu satırı kapattık (Hata vermesin diye)
# RUN go mod download

# Kodları kopyala
COPY . .

# Derle
RUN go build -o scout ./cmd/scout/main.go

# --- Aşama 2: Çalıştırma (Runner) ---
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/scout .

CMD ["./scout"]