# --- Aşama 1: İnşaat (Builder) ---
FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod ./
# RUN go mod download (Şimdilik kapalı)

COPY . .

# Commander'ı derle
RUN go build -o commander ./cmd/commander/main.go

# --- Aşama 2: Çalıştırma (Runner) ---
FROM alpine:latest

WORKDIR /root/

# 1. Uygulamanın kendisini al
COPY --from=builder /app/commander .

# 2. KRİTİK ADIM: Web arayüzü klasörünü içeri kopyala
COPY web ./web

# 8080 portunu aç
EXPOSE 8080

CMD ["./commander"]